export const menuItems=[
    {
        title:'Bangalore Tomato (Thakkali)',
        price:45,
        description:'Red Onions ',
        banner:'https://5.imimg.com/data5/SELLER/Default/2020/9/RS/GB/GF/13355905/banglore-tomato-500x500.jpg',
        category:'fruit',
    },
    {
        title:'Beans (Beans)',
        price:80,
        description:'Red Onions ',
        banner:'https://static.toiimg.com/thumb/msid-71233243,imgsize-562395,width-800,height-600,resizemode-75/71233243.jpg',
        category:'nuts',
    },
    {
        title:'Beetroot (Beetroot)',
        price:45,
        description:'Red Onions ',
        banner:'https://vovamvegetables.in/wp-content/uploads/2020/09/Buy-Beatroot-Nashik.jpg',
        category:'root',
    },
    {
        title:'Bitter Gourd (Pavakkai)',
        price:60,
        description:'Red Onions ',
        banner:'https://images-na.ssl-images-amazon.com/images/I/61nUP47UL%2BL._SX466_.jpg',
        category:'kaya',
    },
    {
        title:'Bottle Gourd (Suraikai)',
        price:20,
        description:'Red Onions ',
        banner:'https://storage.firstik.com/wp-content/uploads/2020/07/10110020/suraikaai.jpg',
        category:'kaya',
    },
    {
        title:'Brinjal (Kathirikkai)',
        price:40,
        description:'Red Onions ',
        banner:'https://herbsandpulses.files.wordpress.com/2020/09/egg-plant.jpg?w=400',
        category:'kaya',
    },
    {
        title:'Broad Beans (Avarakkai)',
        price:45,
        description:'Red Onions ',
        banner:'https://ezgroceria.com/wp-content/uploads/2019/01/VEG-040.jpg',
        category:'nuts',
    },
    {
        title:'Cabbage (Muttaikose)',
        price:25,
        description:'Red Onions ',
        banner:'https://media.istockphoto.com/photos/green-cabbage-isolated-on-white-picture-id673162168?k=6&m=673162168&s=612x612&w=0&h=Rqa0RQ7mcnb7L8S1GZuorSP7BsnKCDaN_leJA5HlLeo=',
        category:'leaves',
    },

    {
        title:'Capsicum (Kudamilagai)',
        price:55,
        description:'Red Onions ',
        banner:'https://zonefresh.com.au/wp-content/uploads/green-capsicum.jpg',
        category:'kaya',
    },
    {
        title:'Carrot (Carrot)',
        price:50,
        description:'Red Onions ',
        banner:'https://images-na.ssl-images-amazon.com/images/I/71S6oQqVa5L._SL1500_.jpg',
        category:'root',
    },
    {
        title:'Cauliflower (Cauliflower)',
        price:45,
        description:'Red Onions ',
        banner:'https://i1.wp.com/www.eatthis.com/wp-content/uploads//media/images/ext/407850298/whole-cauliflower.jpg?fit=1024%2C750&ssl=1',
        category:'flower',
    },
    {
        title:'Chayote (Chow Chow)',
        price:35,
        description:'Red Onions ',
        banner:'https://assets.epicurious.com/photos/57fd1faabb27c57c7c67345c/master/pass/sauteed-chayote-with-garlic-and-herbs.jpg',
        category:'kaya',
    },
    {
        title:'Colocasia (Seppankilangu)',
        price:50,
        description:'Red Onions ',
        banner:'https://communityfarm.in/wp-content/uploads/2018/10/arbi-tubers.jpeg',
        category:'root',
    },
    {
        title:'Coriander Leaves (Kothamalli)',
        price:20,
        description:'Red Onions ',
        banner:'https://5.imimg.com/data5/BG/LC/MY-30125612/coriander-leaves-500x500.jpg',
        category:'leaves',
    },
    {
        title:'Cucumber (Vellarikka)',
        price:30,
        description:'Red Onions ',
        banner:'https://www.lima-europe.eu/wp-content/uploads/2017/04/Cucumber.jpg',
        category:'kaya',
    },
    {
        title:'Drumstick (Murungakkai)',
        price:60,
        description:'Red Onions ',
        banner:'https://falconfresh.com/5597-large_default/drumstick-online-delivery-dubai.jpg',
        category:'kaya',
    },
    {
        title:'Ginger (Inji)',
        price:40,
        description:'Red Onions ',
        banner:'https://www.thespruceeats.com/thmb/QxqFC_PtR8hR7I9-tsCB3S9b7R8=/2128x1409/filters:fill(auto,1)/GettyImages-116360266-57fa9c005f9b586c357e92cd.jpg',
        category:'root',
    },
    {
        title:'Green Chili (Pachai Milagai)',
        price:40,
        description:'Red Onions ',
        banner:'https://5.imimg.com/data5/TU/NL/MY-28500019/fresh-green-chilli-500x500.jpg',
        category:'kaya',
    },
    {
        title:'Green Plantain (Valakkai)',
        price:10,
        description:'Red Onions ',
        banner:'https://www.farmfreshhandpicked.com/pub/media/catalog/product/cache/61f4cbf5acaf9c69e4b207aadb12f207/r/a/raw-banana.jpg',
        category:'kaya',
    },
    {
        title:'Kohlrabi (Nookal)',
        price:25,
        description:'Red Onions ',
        banner:'https://sigarammart.com/wp-content/uploads/2020/08/Kohlrabi-Nookal-%E2%80%93-1kg.jpg',
        category:'root',
    },
    {
        title:'Ladies Finger (Vendakkai)',
        price:35,
        description:'Red Onions ',
        banner:'https://5.imimg.com/data5/BX/HH/GLADMIN-42159570/fresh-lady-finger-vendakkai-500x500.png',
        category:'kaya',
    },
    {
        title:'Mint (Pudina)',
        price:10,
        description:'Red Onions ',
        banner:'https://5.imimg.com/data5/UJ/CW/CP/ANDROID-12352081/product-jpeg-500x500.jpg',
        category:'Leaves',
    },
    {
        title:'Onion (Vengayam)',
        price:25,
        description:'Red Onions ',
        banner:'https://www.nydailynews.com/resizer/BTX_xK-CVPTWFJFaQ8_tKBpqRfM=/1200x0/center/bottom/cloudfront-us-east-1.images.arcpublishing.com/tronc/YKLWDFKDVVCNHHB3DAYOOFLG7I.jpg',
        category:'root',
    },
    {
        title:'Onion (Small) (Chinna Vengayam)',
        price:70,
        description:'Red Onions ',
        banner:'https://sukanfood.com/wp-content/uploads/2019/09/Small-Onion.png',
        category:'root',
    },
    {
        title:'Plantain Flower (Vazhaipoo)',
        price:25,
        description:'Red Onions ',
        banner:'https://www.floraqueen.com/blog/wp-content/uploads/2020/01/shutterstock_696032743.jpg',
        category:'flower',
    },
    {
        title:'Plantain Stem (Vazhaithandu)',
        price:10,
        description:'Red Onions ',
        banner:'https://www.greenfrsh.com/wp-content/uploads/2017/02/banana-stem-600x600.jpg',
        category:'stem',
    },
    {
        title:'Potato (Urulaikilangu)',
        price:20,
        description:'Red Onions ',
        banner:'https://gpi-degouwe.com/wp-content/uploads/2020/06/Potatoes.jpg',
        category:'root',
    },
    {
        title:'Pumpkin (Poosanikai)',
        price:20,
        description:'Red Onions ',
        banner:'https://fruitspice.in/wp-content/uploads/2019/10/pumkin_-_red_1.jpg',
        category:'kaya',
    },
    {
        title:'Radish (Mullangi)',
        price:30,
        description:'Red Onions ',
        banner:'https://5.imimg.com/data5/YY/ID/SR/SELLER-107655683/raddish-wholesaler-in-ahmedabad-500x500.jpg',
        category:'root',
    },
    {
        title:'Ridge Gourd (Peerkangai)',
        price:20,
        description:'Red Onions ',
        banner:'https://lh3.googleusercontent.com/proxy/y3E2KJyn-zdIrz2cZmwqrYslPEXUWm9iMTWdI7RSwr8tcQOQLBtK0EpcKEu-zytgMmX3DWWt3It4-ep35p8xoCYVoAlTb9OeZEia_XJGynsh5ze5M33sz-I-9tQ5FgFJ616skCfnuqb6msIr9Ru24k8QoKroG2GJ',
        category:'kaya',
    },
    {
        title:'Scarlet Gourd (Kovakkai)',
        price:25,
        description:'Red Onions ',
        banner:'https://uzhavanonline.com/wp-content/uploads/2019/01/ivy-gourd.png',
        category:'kaya',
    },
    {
        title:'Snake Gourd (Pudalangai)',
        price:25,
        description:'Red Onions ',
        banner:'https://static.toiimg.com/photo/79265520.cms',
        category:'kaya',
    },
    {
        title:'Sweet Potato (Sakkaravalli Kizhangu)',
        price:30,
        description:'Red Onions ',
        banner:'https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/at%2Farchive%2F8812190bf4f724878a4520f2a60b48ff9d99798e',
        category:'root',
    },
    {
        title:'Tapioca (Maravalli Kizhangu)',
        price:25,
        description:'Red Onions ',
        banner:'https://tiimg.tistatic.com/fp/1/006/056/fresh-tapico-715.jpg',
        category:'root',
    },
    {
        title:'Tomato (Thakkali)',
        price:40,
        description:'Red Onions ',
        banner:'https://3680ebd478ea504d0c91-fcdd7c10a736b671537f0d814c4bbb93.ssl.cf1.rackcdn.com/fresh-tomato-1046527.jpg',
        category:'fruit'
    },
    {
        title:'Yam (Karunai Kilangu)',
        price:75,
        description:'Red Onions ',
        banner:'https://i0.wp.com/www.yummytummyaarthi.com/wp-content/uploads/2013/02/IMG_6246-Copy.jpg?ssl=1',
        category:'root'
    },

]